Repository HXSecurity/DongTai, pull requests merged in 2021-09, with the labels that each got.

#202 fix README.MD typo
  README.MD
Labels: documentation

#212 fix: Grant read/write permission to volume in some uncertain Linux.
  build_with_docker_compose.sh
Labels: bug, enhancement

#226 bug/issue-225
  build_with_docker_compose.sh
Labels: documentation

#227 update repo notify time
  .github/workflows/repository_notify.yml
Labels: enhancement
