Repository HXSecurity/DongTai, pull requests merged in 2022-06, with the labels that each got.

#637 Dongtai engine/filter
  dongtai_common/engine/vul_engine.py
  dongtai_engine/filters/__init__.py
  dongtai_engine/filters/utils.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tests.py
Labels: size/M

#639 sca license
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/dongtai_sca/views/package_vul.py
  dongtai_web/serializers/sca.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
Labels: size/L

#641 refactor/versioncontrol-revert
  dongtai_web/urls.py
  dongtai_web/versioncontrol/__init__.py
  dongtai_web/versioncontrol/admin.py
  dongtai_web/versioncontrol/apps.py
  dongtai_web/versioncontrol/models.py
  dongtai_web/versioncontrol/tests.py
  dongtai_web/versioncontrol/urls.py
  dongtai_web/versioncontrol/views.py
Labels: size/M

#644 feature/agent-list-show-agent-version
  dongtai_web/views/agents_v2.py
Labels: size/XS

#645 plugin/add-log
  dongtai_conf/plugin/__init__.py
Labels: size/S

#642 enhanchment/engine-filter-trust-boundary-violation
  dongtai_engine/filters/main.py
  dongtai_engine/tasks.py
  dongtai_engine/tests.py
Labels: size/S

#646 Feature/vul distinct change
  dongtai_common/models/vulnerablity.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
Labels: size/L

#648 Update version_update.py
  deploy/docker/version_update.py
Labels: size/XS

#649 vul-scan/unvalidated-redirect-filter
  dongtai_engine/filters/main.py
Labels: size/XS

#650 feature/saas_method_pool_api_route_record
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/report/handler/utils.py
  dongtai_protocol/tests.py
Labels: size/M

#652 bugix
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#654 feature/saas_method_pool_api_route_record
  dongtai_common/models/api_route.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/S

#655 feature/saas_method_pool_api_route_recordv2
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#656 feature/saas_method_pool_api_route_recordv4
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#651 Update Dockerfile
  Dockerfile
Labels: size/XS

#653 Bidaya0 patch readme document tree
  README-zh.md
  README.md
Labels: size/M

#657 remove-apitest
  dongtai_web/apitest/__init__.py
  dongtai_web/apitest/admin.py
  dongtai_web/apitest/apps.py
  dongtai_web/apitest/models.py
  dongtai_web/apitest/tests.py
  dongtai_web/apitest/urls.py
  dongtai_web/apitest/utils.py
  dongtai_web/apitest/views.py
  dongtai_web/urls.py
Labels: size/L

#658 bugfix/parameter-validaterm
  dongtai_web/threshold/config_setting.py
  dongtai_web/views/log_download.py
Labels: size/XS

#659 fix:vul_save_change_distinct_logic
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
Labels: size/S

#660 sca sata
  dongtai_common/models/asset_vul.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/sca_handler.py
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/models.py
  dongtai_web/dongtai_sca/tasks.py
  dongtai_web/dongtai_sca/utils.py
Labels: size/L

#662 fix
  dongtai_web/dongtai_sca/common/sca_vul.py
Labels: size/XS

#663 update dtctl
  .github/workflows/release_dongtai.yml
  .github/workflows/release_helm_chart.yml
  deploy/docker-compose/docker-compose.yml.example
  deploy/docker-compose/dtctl
  deploy/docker-compose/nginx.conf
Labels: size/L

#668 sca vul list
  dongtai_common/models/__init__.py
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/S

#669 bind_project_id>0
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/XS

#670 iast asset _project_id>0
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
Labels: size/XS

#671 Update Dockerfile
  Dockerfile
Labels: size/XS

#672 update dtctl
  deploy/docker-compose/dtctl
Labels: size/S

#673 fix asset
  dongtai_common/models/sca_artifact_db.py
  dongtai_common/models/sca_maven_artifact.py
  dongtai_common/models/sca_record.py
  dongtai_common/models/sca_vul_db.py
  dongtai_engine/tasks.py
  dongtai_web/dongtai_sca/utils.py
  dongtai_web/scaupload/urls.py
  dongtai_web/scaupload/views.py
  dongtai_web/views/sca_details.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
Labels: size/L

#676 threshold-prority-change
  dongtai_protocol/views/agent_config.py
Labels: size/XS

#677 debug summary version and default
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/M

#674 fix sql
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
Labels: size/L

#679 Temporary/disable summary cache
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/apps.py
Labels: size/S

#680 temprorary/disable-method-pool-logging
  dongtai_protocol/report/report_handler_factory.py
Labels: size/XS

#682 fix: volume
  deploy/docker-compose/dtctl
Labels: size/S

#684 bugfix/log_download-when-log-file-not-found
  dongtai_web/views/log_download.py
Labels: size/S

#685 Feature/param name mark extend taint value range
  dongtai_engine/signals/handlers/parse_param_name.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tests.py
Labels: size/L

#686 feature/param-name-mark-change-match-way
  dongtai_engine/signals/handlers/parse_param_name.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tests.py
Labels: size/M

#689 dongtai-engine/filter/reflection-injection
  dongtai_engine/filters/main.py
Labels: size/XS

#690 Update main.py
  dongtai_engine/filters/main.py
Labels: size/XS

#691 dongtai-engine/filter/unsafe-json-deserialize-fastjson
  dongtai_engine/filters/main.py
  dongtai_engine/tasks.py
  requirements-prod.txt
Labels: size/S

#688 fix asset scan vul_list
  dongtai_web/dongtai_sca/utils.py
  dongtai_web/serializers/sca.py
Labels: size/L

#692 Backup 1.8.0
  dongtai_web/dongtai_sca/utils.py
  dongtai_web/serializers/sca.py
Labels: size/L

#693 fix dependency
  dongtai_engine/tasks.py
Labels: size/XS

#696 bugfix/agent-register-version-name-validate
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#697 Backup 1.8.0
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#698 Backup 1.8.0
  deploy/docker-compose/docker-compose.yml.example
  deploy/docker-compose/dtctl
  deploy/kubernetes/helm/templates/deployment-dongtai.yml
  deploy/kubernetes/manifest/4.deploy-iast-server.yml
Labels: size/M

#705 fix dependency
  dongtai_engine/tasks.py
Labels: size/XS

#707 fix introduced
  dongtai_web/dongtai_sca/utils.py
Labels: size/XS

#709 fix vul list
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/XS

#713 Bugfix/fix vul assetname
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/utils.py
Labels: size/XS

#714 fix vul asset
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#718 sca vul list order by created_time debug
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#717 Update agents_v2.py
  dongtai_web/views/agents_v2.py
Labels: size/XS

#720 change/disable-pagination-in-circuit_config
  dongtai_web/threshold/config_setting.py
Labels: size/S

#724 vul_list-change
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/S

#723 fix bug when k8s install server
  deploy/kubernetes/install.sh
Labels: size/XS

#725 feature/add-disk
  dongtai_protocol/report/handler/heartbeat_handler.py
Labels: size/XS

#728 fix: helm CI
  .github/workflows/release_helm_chart.yml
Labels: size/S

#727 Elasticsearch final
  batect.yml
  dongtai_common/models/agent_method_pool.py
  dongtai_common/models/asset.py
  dongtai_common/models/asset_aggr.py
  dongtai_common/models/asset_vul.py
  dongtai_common/models/vulnerablity.py
  dongtai_conf/conf/config.ini.example
  dongtai_conf/conf/config.ini.test
  dongtai_conf/settings.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/utils.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
  requirements-prod.txt
Labels: size/XXL

#719 Elasticsearch method pool
  dongtai_common/models/agent_method_pool.py
  dongtai_conf/settings.py
  dongtai_web/views/engine_method_pool_search.py
Labels: size/L

#729 change-key-name-to-keep-compatibility
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/XS

#730 bugfix:change-filter-key
  dongtai_web/views/sca_summary.py
Labels: size/XS

#731 bugfix/engine-method-pool-search-req_header-fs
  dongtai_web/views/engine_method_pool_search.py
Labels: size/XS

#734 feature/es-level-order
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/XS

#736 expirement/add-es-settings
  dongtai_conf/settings.py
Labels: size/XS

#737 expirement/test-engine-task-change
  deploy/docker/entrypoint.sh
Labels: size/XS

#738 expirement/change-elastic-search-logging-level
  dongtai_conf/settings.py
Labels: size/XS

#739 expirement/change-vul_save-logic
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/S

#740 expirement/change-vul_save-logic-v2
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/S

#741 expirement/change-vul_save-logic-v2-fix
  dongtai_engine/plugins/strategy_headers.py
Labels: size/XS

#742 Expirement/add celery handler
  dongtai_common/utils/es.py
  dongtai_conf/settings.py
Labels: size/S

#743 expirement/add-log-settings
  dongtai_common/utils/es.py
  dongtai_conf/celery.py
Labels: size/XS

#744 expirement/celery-handler-fix
  dongtai_common/utils/es.py
Labels: size/XS

#745 bug/fix-es-vuln-field
  dongtai_common/models/vulnerablity.py
Labels: size/XS

#746 es-implement/add-autorefresh
  dongtai_common/models/asset_vul.py
  dongtai_common/models/vulnerablity.py
Labels: size/XS

#747 elastic-search/es-shards
  dongtai_common/models/asset.py
  dongtai_common/models/asset_vul.py
  dongtai_common/models/vulnerablity.py
Labels: size/M

#748 bugfix-es-app_vul_summary-data-incorrect
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/S

#749 bugfix/preheat-error-when-user-was-deleted
  dongtai_engine/preheat.py
Labels: size/XS

#750 restore-old-deploy/docker/entrypoint.sh
  deploy/docker/entrypoint.sh
Labels: size/XS

#752 Elastic search/data correction
  dongtai_conf/celery.py
  dongtai_engine/elatic_search/__init__.py
  dongtai_engine/elatic_search/data_correction.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/M

#754 elasticsearch/batch-insert
  dongtai_common/utils/es.py
  dongtai_conf/celery.py
  dongtai_conf/settings.py
Labels: size/M

#758 elastic-search/batchupdate-v3
  dongtai_common/utils/es.py
Labels: size/XS
