Repository HXSecurity/DongTai, pull requests merged in 2022-05, with the labels that each got.

#587 change batect.yml
  batect.yml
Labels: size/XS

#588 feature/agent_config_threshold_v2
  apiserver/urls.py
  apiserver/views/agent_config.py
  requirements-prod.txt
Labels: size/M

#589 feature/agent_config_v2 base
  apiserver/views/agent_config.py
  dongtai/models/agent_config.py
  iast/threshold/config_setting.py
  iast/urls.py
  test/apiserver/test_config.py
Labels: size/L

#590 add enum api
  apiserver/views/agent_config.py
  dongtai/models/agent_config.py
  iast/tests.py
  iast/threshold/config_setting.py
  iast/urls.py
Labels: size/L

#591 bugfix/agent-config-v2
  apiserver/views/agent_config.py
Labels: size/XS

#592 fix:筛选未运行的agent却筛选出了全部agent
  iast/views/agents.py
Labels: size/XS

#585 Save method pool data using log service
  apiserver/report/handler/saas_method_pool_handler.py
  apiserver/report/log_service.py
  apiserver/report/report_handler_factory.py
  conf/config.ini.example
  conf/config.ini.test
  core/tasks.py
  webapi/settings.py
Labels: size/L

#593 fixes replay method pool send to engine
  apiserver/report/handler/saas_method_pool_handler.py
Labels: size/XS

#595 Feature/agent config v2 final
  apiserver/views/agent_config.py
  dongtai/models/agent_config.py
  iast/threshold/config_setting.py
  iast/urls.py
  test/apiserver/test_config.py
  webapi/settings.py
Labels: size/L

#598 fix:image not found error in Linux shell
  deploy/kubernetes/install.sh
Labels: size/S

#583 Add log collection scheme
  deploy/docker-compose/docker-compose.yml.example
  deploy/docker-compose/logrotate
  deploy/docker-compose/logstash.conf
Labels: size/M

#605 fix:筛选未运行的agent却筛选出了全部agent
  iast/views/agents.py
Labels: size/XS

#607 add vul list pro info
  iast/aggr_vul/aggr_vul_list.py
Labels: size/XS

#608 sca summary list
  iast/aggr_vul/aggr_vul_summary.py
Labels: size/M

#609 revert-me
  iast/account/department.py
  iast/account/talent.py
  iast/account/user.py
  iast/urls.py
Labels: size/XL

#611 remove-report
  core/plugins/export_report.py
  core/tasks.py
  iast/urls.py
  iast/views/project_report_delete.py
  iast/views/project_report_download.py
  iast/views/project_report_export.py
  iast/views/project_report_list.py
  iast/views/project_report_sync_add.py
  iast/views/sca_export.py
Labels: size/XXL

#614 Update deploy-dev.yaml
  .github/workflows/ApiTest.yml
  .github/workflows/deploy-dev.yaml
Labels: size/XS

#615 Repair test environment
  .github/deploy/deploy-dongtai-server-test.yml
Labels: size/S

#616 Update uwsgi.ini
  dongtai_conf/conf/uwsgi.ini
Labels: size/XS

#619 celery-boot
  dongtai_conf/settings.py
Labels: size/XS

#620 celery-boot-v2
  dongtai_conf/settings.py
  dongtai_web/apps.py
Labels: size/XS

#618 update devops
  .github/deploy/deploy-dongtai-server-prod.yml
  .github/deploy/deploy-dongtai-server-test.yml
  .github/workflows/ApiTest.yml
  .github/workflows/ApiTestwithiast.yml
  Dockerfile
  deploy/docker-compose/config-tutorial.ini
  deploy/docker-compose/docker-compose.yml.example
  deploy/docker-compose/logrotate
  deploy/docker-compose/logstash.conf
  deploy/docker-compose/nginx.conf
  deploy/kubernetes/manifest/4.deploy-iast-server.yml
  dongtai_conf/conf/config.ini.example
  dongtai_conf/conf/uwsgi.ini
Labels: size/L

#621 update action
  deploy/docker/entrypoint.sh
  deploy/docker/version_update.py
Labels: size/S

#622 Update Dockerfile
  Dockerfile
Labels: size/S

#624 feature:change-to-show-api-collect-by-server-side
  dongtai_web/views/api_route_cover_rate.py
  dongtai_web/views/api_route_search.py
Labels: size/XS

#625 add action cp
  .github/workflows/ApiTest.yml
  .github/workflows/dongtai-devops-pr.yaml
  .github/workflows/dontai-devops-cp.yaml
  deploy/docker-compose/dtctl
  dongtai_conf/conf/config.ini.test
Labels: size/M

#617 clean celery tasks
  deploy/docker/entrypoint.sh
  dongtai_conf/celery.py
  dongtai_engine/preheat.py
  dongtai_engine/tasks.py
  dongtai_engine/web_hook.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_web/dongtai_sca/tasks.py
Labels: size/L

#627 feature/agent-update
  dongtai_protocol/views/engine_status.py
Labels: size/XS

#629 bugfix/agent_core_status_agent_ids_missing
  batect.yml
  dongtai_web/threshold/agent_core_status.py
  dongtai_web/views/__init__.py
Labels: size/S

#628 The engine era is over，start worker!!!
  .github/deploy/deploy-dongtai-server-test.yml
  .github/workflows/config/.dlc.json
  .github/workflows/dongtai-devops-pr.yaml
  deploy/docker-compose/dtctl
Labels: size/L

#631 update_common_file_path
  .github/workflows/ApiTestwithiast.yml
  Dockerfile
  dongtai_conf/conf/config.ini.example
Labels: size/XS

#632 feature/agent-update-v2
  dongtai_protocol/views/engine_status.py
Labels: size/S

#634 feature/log_download_batch
  dongtai_common/models/message.py
  dongtai_web/tests.py
  dongtai_web/urls.py
  dongtai_web/views/log_download.py
Labels: size/M
