Repository HXSecurity/DongTai, pull requests merged in 2022-04, with the labels that each got.

#534 fix report output settings
  core/plugins/export_report.py
  core/tasks.py
  sca/models.py
  test/core/tasks.py
  webapi/settings.py
Labels: size/M

#536 ignore add docker
  .gitignore
  docker/entrypoint.sh
  docker/version.sql
  docker/version.sql.example
  docker/version_update.py
Labels: size/M

#538 fix report error bug
  core/plugins/export_report.py
  core/tasks.py
Labels: size/M

#539 fix report stop bug by data
  core/plugins/export_report.py
  core/tasks.py
  test/core/tasks.py
  upload/reports/report.example
Labels: size/S

#540 del some log of debug report
  apiserver/report/handler/saas_method_pool_handler.py
  apiserver/report/report_handler_factory.py
  core/plugins/export_report.py
Labels: size/M

#541 fix report bug no dictionary
  .gitignore
  core/tasks.py
  upload/reports/pdf.example
Labels: size/XS

#543 fix:add upgrade and install for latest image
  .gitignore
  deploy/docker-compose/dtctl
  deploy/docker-compose/test/test_dtctl.bats
  deploy/latest_image.sh
Labels: size/L

#545 develop: change batect setting to follow new deploy way
  batect.yml
Labels: size/XS

#546 bugfix: hook_profiles check strategy state and hooktype state now
  apiserver/views/hook_profiles.py
Labels: size/S

#547 fix:support different version tag in k8s installation
  deploy/docker-compose/dtctl
  deploy/kubernetes/install.sh
Labels: size/M

#548 fix:miss tag when dtctl rm -d
  deploy/docker-compose/dtctl
Labels: size/XS

#549 optimise/add-celery-task-when-report-upload-instead-call-engine-api
  apiserver/report/handler/saas_method_pool_handler.py
  core/tasks.py
Labels: size/S

#550 fix:upgade docker-compose.yml.example defautl port to 80
  deploy/docker-compose/docker-compose.yml
  deploy/docker-compose/docker-compose.yml.example
Labels: size/M

#552 feature: vul_detail v2
  iast/urls.py
  iast/views/vul_details.py
Labels: size/M

#553 feature/v2-vul-details-add-url
  iast/views/vul_details.py
Labels: size/XS

#556 bugfix/can't-delete-department-when-its-contains-sub-department
  iast/account/department.py
Labels: size/XS

#557 hotfix:1.4.1-agent-download
  .github/workflows/release_dongtai.yml
  apiserver/views/agent_download.py
  apiserver/views/engine_download.py
Labels: size/XS

#560 feat: add multi vm deploy scripts
  deploy/multi-vm/README.md
  deploy/multi-vm/config-tutorial.ini
  deploy/multi-vm/vm1/nginx.conf
  deploy/multi-vm/vm2/lb.conf
  deploy/multi-vm/vm3/lb.conf
Labels: size/L

#565 add docker-compose file for multi vm deployment
  .gitignore
  deploy/multi-vm/vm1/docker-compose.yml
  deploy/multi-vm/vm2/docker-compose.yml
  deploy/multi-vm/vm3/docker-compose.yaml
Labels: size/M

#569 Optmise/fix log and vul
  dongtai/models/sca_artifact_db.py
  iast/views/sca_details.py
  sca/models.py
  sca/views/package_vul.py
  signals/handlers/vul_handler.py
  test/core/tasks.py
  webapi/settings.py
Labels: size/M

#570 optimise/use-orm-forgeinkey-to-enable-join
  dongtai/models/agent.py
Labels: size/XS

#571 bugfix: replay queue logic change
  apiserver/report/handler/heartbeat_handler.py
Labels: size/M

#572 feature: agent list 2.0
  iast/tests.py
  iast/urls.py
  iast/views/agents_v2.py
Labels: size/L

#573 Feature/agent protocol
  apiserver/views/agent_register.py
  apiserver/views/agent_update.py
  dongtai/models/server.py
Labels: size/M

#574 feature:agent_core_status_change_all
  apiserver/report/handler/heartbeat_handler.py
  iast/threshold/agent_core_status.py
  iast/urls.py
Labels: size/M

#575 feature: add global threshold config
  dongtai/utils/systemsettings.py
  iast/threshold/get_config_setting.py
Labels: size/S

#576 bugfix/global-threshold-config-change
  apiserver/views/agent_config.py
  iast/threshold/get_config_setting.py
Labels: size/XS

#561 performace and engine request merge
  .gitignore
  Dockerfile
  apiserver/report/handler/api_route_handler.py
  apiserver/report/handler/heartbeat_handler.py
  apiserver/report/handler/report_handler_interface.py
  apiserver/report/handler/saas_method_pool_handler.py
  apiserver/report/handler/sca_handler.py
  apiserver/report/report_handler_factory.py
  apiserver/views/hook_profiles.py
  apiserver/views/report_upload.py
  conf/uwsgi.ini
  core/plugins/export_report.py
  core/plugins/strategy_sensitive.py
  core/tasks.py
  deploy/docker-compose/nginx.conf
  docker/entrypoint.sh
  dongtai/endpoint/__init__.py
  requirements-prod.txt
  requirements-test.txt
  signals/handlers/vul_handler.py
  test/core/tasks.py
  webapi/settings.py
Labels: size/L

#581 add reports ignore
  .gitignore
  upload/reports/.gitignore
Labels: size/XS

#582 add notify config model
  dongtai/models/notify_config.py
  iast/upload/reports/report.example
Labels: size/S
