Repository HXSecurity/DongTai, pull requests merged in 2022-07, with the labels that each got.

#759 elastic-search/model-bindingchange
  dongtai_common/models/asset.py
  dongtai_common/models/asset_vul.py
  dongtai_common/models/vulnerablity.py
Labels: size/XS

#760 elastic-search-batch-write-change
  dongtai_common/utils/es.py
Labels: size/XS

#762 expirement/upgrage-redis-4.3.2
  requirements-prod.txt
Labels: size/XS

#763 Revert "expirement/upgrage-redis-4.3.2"
  requirements-prod.txt
Labels: size/XS

#764 Redis change to multi
  dongtai_common/utils/es.py
Labels: size/XS

#765 dongtai_common/rate-limit-change
  dongtai_common/utils/es.py
Labels: size/XS

#766 elasticsearch/change-redis-process
  dongtai_common/utils/es.py
Labels: size/XS

#767 elasticsearch/change-es-save
  dongtai_common/utils/es.py
Labels: size/S

#768 elastic-search/batchupdate-v3-bugfix
  dongtai_common/utils/es.py
Labels: size/XS

#769 celery-change
  .github/deploy/deploy-dongtai-server-test.yml
  deploy/docker/entrypoint.sh
  requirements-prod.txt
Labels: size/S

#770 change-celery-to-eventlet
  deploy/docker/entrypoint.sh
  requirements-prod.txt
Labels: size/XS

#771 Revert vul scan celery settings
  deploy/docker/entrypoint.sh
Labels: size/XS

#772 seprate-sca
  deploy/docker/entrypoint.sh
Labels: size/XS

#773 fix: es sca
  .github/deploy/deploy-dongtai-server-test.yml
Labels: size/M

#776 Update settings.py
  dongtai_conf/settings.py
Labels: size/XS

#778 Update deploy-dongtai-server-test.yml
  .github/deploy/deploy-dongtai-server-test.yml
Labels: size/XS

#779 specification
  .github/deploy/deploy-dongtai-server-test.yml
  deploy/docker/entrypoint.sh
Labels: size/M

#780 bugfix/sca-bulk-create-es-save-changed
  dongtai_web/dongtai_sca/utils.py
Labels: size/S

#781 Update deploy-dongtai-server-test.yml
  .github/deploy/deploy-dongtai-server-test.yml
Labels: size/XS

#785 Feature/system core clean
  dongtai_conf/celery.py
  dongtai_conf/settings.py
  dongtai_engine/plugins/data_clean.py
  dongtai_web/systemmonitor/__init__.py
  dongtai_web/systemmonitor/data_clean.py
  dongtai_web/systemmonitor/urls.py
  dongtai_web/urls.py
Labels: size/L

#786 bugfix/aggr_vul_list-field-keyerror
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#787 bugfix/app_vul_list-when-agnet-missing
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/S

#788 bugfix/aggregation-ser-field-validator-fix
  dongtai_web/serializers/aggregation.py
Labels: size/XS

#789 bugfix/threshold/config_setting-enumname-fix
  dongtai_web/threshold/config_setting.py
Labels: size/XS

#782 Sca list change
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/serializers/sca.py
  dongtai_web/views/scas.py
Labels: size/L

#790 Update asset_projects.py
  dongtai_web/dongtai_sca/views/asset_projects.py
Labels: size/XS

#791 Update package_vul.py
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/XS

#792 Revert "Update asset_projects.py"
  dongtai_web/dongtai_sca/views/asset_projects.py
Labels: size/XS

#793 Revert "Revert "Update asset_projects.py""
  dongtai_web/dongtai_sca/views/asset_projects.py
Labels: size/XS

#794 sca-list-fix
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/dongtai_sca/views/package_vul.py
  dongtai_web/serializers/sca.py
Labels: size/S

#795 bugfix-add-new-field-to-es
  dongtai_common/models/asset_vul.py
Labels: size/XS

#796 bugfix/scas-list-bugfix
  dongtai_web/views/scas.py
Labels: size/XS

#797 bugfix-sca-list
  dongtai_web/views/scas.py
Labels: size/XS

#798 bugfix/sca-list
  dongtai_web/views/scas.py
Labels: size/XS

#799 vul-scan-replace-temporaryfile-with-bytesio
  dongtai_engine/filters/utils.py
Labels: size/XS

#801 optimise/data-clean
  dongtai_engine/plugins/data_clean.py
Labels: size/M

#802 bugfix/data-clean
  dongtai_engine/plugins/data_clean.py
Labels: size/XS

#803 expirement/gevent-change-high-freq
  .github/deploy/deploy-dongtai-server-test.yml
  dongtai_conf/settings.py
Labels: size/S

#804 bugfix/replace-too-slow-auth-checking-method
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/S

#805 bugfix/scas-keyword-search
  dongtai_web/views/scas.py
Labels: size/XS

#809 bugfix/convert-orm-filter
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#811 setting-list-hosts
  dongtai_conf/settings.py
Labels: size/XS

#816 bugfix/param-validator-in-aggr
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/XS

#818 bugfix-validator-in-aggr-list
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/serializers/aggregation.py
Labels: size/M

#819 bugfix/strategy-curd-id-filter-change-v2
  dongtai_web/views/strategy_delete.py
  dongtai_web/views/strategy_modified.py
Labels: size/S

#820 bugfix/strategy-curd-id-filter-change-v3
  dongtai_web/views/strategy_delete.py
  dongtai_web/views/strategy_modified.py
Labels: size/XS

#821 develop-enable-dongtai-agent-in-daily-api-test
  dongtai_conf/settings.py
Labels: size/XS

#822 feature/agent-action-v3
  dongtai_common/models/agent.py
  dongtai_protocol/report/report_handler_factory.py
  dongtai_protocol/urls.py
  dongtai_protocol/views/agent_update.py
  dongtai_protocol/views/except_action.py
  dongtai_web/threshold/agent_core_status.py
  dongtai_web/views/agents_v2.py
Labels: size/L

#823 bugfix/add-filter-to-aviod-exceed-mysql-int-limit
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/XS

#826 enhanchment/change-message-response
  dongtai_common/endpoint/__init__.py
  dongtai_protocol/views/agent_register.py
  dongtai_protocol/views/report_upload.py
  dongtai_web/views/user_passwrd_reset.py
Labels: size/S

#829 bugfix/data-clean-change
  dongtai_engine/plugins/data_clean.py
Labels: size/XS

#834 enhanchment/data_clean-asyncbatch
  dongtai_engine/plugins/data_clean.py
Labels: size/M

#835 enhanchment/data_clean-asyncbatch
  dongtai_engine/plugins/data_clean.py
Labels: size/XS

#836 dependency-fix/drf-spectacular-gis-breaking
  requirements-prod.txt
Labels: size/XS

#837 bugfix/data_clean
  dongtai_engine/plugins/data_clean.py
Labels: size/XS

#839 enhanchment/fusuion-asyncio-and-gevent
  dongtai_conf/settings.py
Labels: size/S

#840 requirement/add-asyncio-gevent-req
  requirements-prod.txt
Labels: size/XS

#841 enhanchement/async-task-data-clean
  dongtai_engine/plugins/data_clean.py
Labels: size/XS

#844 bugfix :begin_num validate failed
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/S

#845 bugfix/runs-7572056392-strategy_modified_level_id_validation
  dongtai_web/views/strategy_modified.py
Labels: size/XS

#846 change keyoffset logic
  dongtai_web/views/scas.py
Labels: size/S

#847 bugfix/order-by-in-scas-group-by-limit
  dongtai_web/views/scas.py
Labels: size/XS

#842 Feature/sca as a service
  dongtai_common/models/asset.py
  dongtai_common/models/asset_vul.py
  dongtai_conf/celery.py
  dongtai_conf/conf/config.ini.example
  dongtai_conf/conf/config.ini.test
  dongtai_conf/settings.py
  dongtai_web/dongtai_sca/scan/__init__.py
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/L

#848 bugfix/typo-in-safe-version
  dongtai_common/models/asset.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#849 new-sca/change-task-position
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/sca_handler.py
Labels: size/XS

#850 bugfix/asset_vul_add_change
  dongtai_engine/tasks.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#851 bugfix/asset_vul_add_changev2
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#852 bugfix/asset_vul_add_changev2
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#853 V
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#854 bugfix/aggr_vul_list-cwe_extract
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/S

#855 version_list_update
  dongtai_common/models/asset.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/serializers/sca.py
Labels: size/S

#856 new-sca/license-list
  dongtai_common/models/asset.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#857 bugfix/sca-version-scan
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#858 add-license-field
  dongtai_web/serializers/sca.py
Labels: size/XS

#859 bugfix:max_version
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#860 change-token-to-config
  dongtai_conf/conf/config.ini.example
  dongtai_conf/conf/config.ini.test
  dongtai_conf/settings.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S
