Repository HXSecurity/DongTai, pull requests merged in 2022-08, with the labels that each got.

#862 change-safe-version
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#863 package-version-fix
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#864 bugfix/description-showing
  dongtai_common/models/asset.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#866 testcase/add-safe-version-testcase
  dongtai_web/dongtai_sca/scan/tests.py
Labels: size/S

#867 bugfix/asset_vul-field-fix
  dongtai_common/models/asset.py
  dongtai_common/models/asset_vul.py
  dongtai_conf/settings.py
  dongtai_web/views/user_info.py
Labels: size/S

#868 bugfix/asset_projects-and-package-vul
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/M

#869 bugfix/cwe_id-name
  dongtai_web/dongtai_sca/scan/cwe.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/L

#870 bugfix/project_name
  dongtai_web/dongtai_sca/common/sca_vul.py
Labels: size/XS

#871 bugfix/project_name-v2
  dongtai_web/dongtai_sca/common/sca_vul.py
Labels: size/S

#872 bugfix-missing-reference
  dongtai_common/models/asset_vul.py
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#873 bugfix/title
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#874 bugfix/reference-fix
  dongtai_web/dongtai_sca/common/sca_vul.py
Labels: size/S

#876 bugfix/reference-fix-v2
  dongtai_web/dongtai_sca/common/sca_vul.py
Labels: size/XS

#878 bugfix/asset/scan-missing-in-db
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#882 sca_setup/status-change
  dongtai_web/views/user_info.py
Labels: size/XS

#883 bugfix/count-is_del-vul
  dongtai_web/serializers/project.py
  dongtai_web/views/utils/commonstats.py
Labels: size/S

#885 es-document-change/asset
  dongtai_common/models/asset.py
Labels: size/S

#886 Revert "es-document-change/asset"
  dongtai_common/models/asset.py
Labels: size/S

#887 es-document-change/assetv2
  dongtai_common/models/asset.py
Labels: size/S

#888 temporary-disable-asset-search
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
Labels: size/S

#889 bugfix/license-list-array-form-to-dict
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#890 bugfix/license-scan
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#892 bugfix/sensetive_info-bugfix-dependency-to-re2
  dongtai_engine/plugins/strategy_sensitive.py
Labels: size/XS

#893 temporary/disable-scas
  dongtai_web/views/scas.py
Labels: size/XS

#894 bugfix/methodpool_search_key
  dongtai_web/views/engine_method_pool_search.py
Labels: size/XS

#895 Bugfix/package vul
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/S

#896 logging/change-log-level
  dongtai_web/views/agents_v2.py
Labels: size/XS

#899 bugfix/aggr_vul_list-distinct
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#897 logging/log-level-down
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_web/views/agents_delete.py
Labels: size/M

#902 unitfy/settings
  dongtai_conf/settings.py
  dongtai_web/views/log_download.py
Labels: size/M

#903 deploy/celery-settings-change
  dongtai_conf/celery.py
  dongtai_conf/settings.py
Labels: size/S

#904 temporary-disable-ssrf-filter
  dongtai_engine/filters/main.py
Labels: size/XS

#906 optimise/package_vul-select-change
  dongtai_web/dongtai_sca/views/package_vul.py
Labels: size/XS

#908 bugfix-dongtai_conf-settings-confilct
  dongtai_conf/settings.py
Labels: size/XS

#905 bridge-divison/part-1
  dongtai_common/common/__init__.py
  dongtai_common/models/__init__.py
  dongtai_common/models/project_report.py
  dongtai_protocol/report/handler/sca_handler.py
  dongtai_web/dongtai_sca/tasks.py
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/serializers/sca.py
  dongtai_web/views/log_clear.py
  dongtai_web/views/log_download.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
  requirements-prod.txt
Labels: size/L

#909 bugfix/sca-other-language-compatibility
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#913 command/user-statistic
  deploy/commands/management/commands/statistics.py
Labels: size/M

#912 sca-scan-v2
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#914 bugfix/remove-row-lock
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#916 dongtai_sca-scan-value
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#918 bugfix/mypy-check
  dongtai_conf/plugin_install.py
  dongtai_engine/filters/utils.py
  dongtai_engine/preheat.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/tests.py
  dongtai_web/threshold/config_setting.py
  dongtai_web/views/agents_v2.py
Labels: size/M

#919 logging/change-log-level-and-message-for-debug
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#920 limit-dtctl-unnitest-in-main
  .github/workflows/dtctl-unittest.yaml
Labels: size/XS

#926 testcase/testcase-fixed
  .github/workflows/UnitTest.yml
  dongtai_engine/tests.py
  dongtai_protocol/tests.py
  requirements-prod.txt
  test/apiserver/test_agent_method_pool.py
  test/iast/views/test_vul_summary.py
Labels: size/M

#930 feature/add-secretmanager-support
  dongtai_conf/settings.py
  dongtai_conf/utils.py
Labels: size/M

#931 Feature/add secretmanager support
  requirements-prod.txt
Labels: size/XS

#933 Feature/add secretmanager support v2
  dongtai_conf/utils.py
Labels: size/XS

#935 feature/add-secretmanager-support
  dongtai_conf/utils.py
Labels: size/XS

#936 feature/add-secretmanager-support
  dongtai_conf/utils.py
Labels: size/XS

#937 Update utils.py
  dongtai_conf/utils.py
Labels: size/XS

#940 Update user_register_batch.py
  dongtai_web/views/user_register_batch.py
Labels: size/XS

#928 feature/path-varible-regonize
  dongtai_common/models/vulnerablity.py
  dongtai_engine/signals/handlers/vul_handler.py
  static/data/java_params.json
Labels: size/L

#941 feature/path-varible-regonize-field-fix
  dongtai_common/models/vulnerablity.py
Labels: size/XS

#943 feature/path-varible-regonize-field-fix-v2
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/XS

#944 feature/sca-project-counts
  dongtai_web/serializers/sca.py
Labels: size/XS

#945 Range detect vul
  dongtai_common/engine/vul_engine.py
  dongtai_engine/filters/main.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  static/data/java_params.json
Labels: size/L
