Repository HXSecurity/DongTai, pull requests merged in 2023-07, with the labels that each got.

#1563 Update README.md
  README-zh.md
  README.md
Labels: size/XS

#1564 deps: add shortuuid as deps .
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/S

#1565 doc: add tags to api extend_schema.
  dongtai_protocol/views/report_upload.py
  dongtai_web/dongtai_sca/views/package.py
  dongtai_web/threshold/config_setting.py
  dongtai_web/views/vul_request_replay.py
  static/i18n/views/setlang.py
  test/debug/management/commands/check_schema.py
Labels: size/M

#1566 feat: merge changes
  dongtai_common/engine/compatibility.py
  dongtai_common/models/url_blacklist.py
  dongtai_common/translation.py
  dongtai_conf/celery.py
  dongtai_conf/conf/config.ini.test
  dongtai_conf/settings.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/__init__.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/signals/signals.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_web/account/__init__.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/apitimelog/views.py
  dongtai_web/apps.py
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/models.py
  dongtai_web/dongtai_sca/tasks.py
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/utils.py
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagedetail.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
  dongtai_web/dongtai_sca/views/newpackagevuldetail.py
  dongtai_web/dongtai_sca/views/newpackagevullevel.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
  dongtai_web/dongtai_sca/views/package.py
  dongtai_web/dongtai_sca/views/package_vul.py
  dongtai_web/serializers/vul.py
  dongtai_web/urls.py
  dongtai_web/views/engine_method_pool_sca.py
  dongtai_web/views/profile.py
  dongtai_web/views/tests.py
  dongtai_web/views/vuls.py
  static/i18n/en/LC_MESSAGES/django.po
  static/i18n/zh/LC_MESSAGES/django.po
  static/templates/pdf.html
  test/core/tasks.py
  test/signals/handlers/vul_handler.py
Labels: size/XXL

#1567 feat: remove some api
  dongtai_conf/celery.py
  dongtai_engine/plugins/data_clean.py
  dongtai_web/projecttemplate/base.py
  dongtai_web/systemmonitor/data_clean.py
  dongtai_web/systemmonitor/urls.py
  dongtai_web/urls.py
  dongtai_web/views/scan_strategys.py
  test/iast/views/test_scan_strategy.py
Labels: size/XL

#1568 refactor: remove match statement
  dongtai_common/endpoint/__init__.py
Labels: size/S

#1569 fix: agent status log
  dongtai_engine/tasks.py
Labels: size/XS

#1570 feat: remove some api
  dongtai_web/dast/__init__.py
  dongtai_web/dast/manage.py
  dongtai_web/dast/mockdata/method_pool.pickle
  dongtai_web/dast/page.py
  dongtai_web/dast/tests.py
  dongtai_web/dast/webhook.py
  dongtai_web/project/__init__.py
  dongtai_web/project/recognize_rule.py
  dongtai_web/tests.py
  dongtai_web/threshold/__init__.py
  dongtai_web/threshold/agent_core_status.py
  dongtai_web/threshold/config_setting.py
  dongtai_web/threshold/del_threshold_setting.py
  dongtai_web/threshold/del_webhook_setting.py
  dongtai_web/threshold/get_config_setting.py
  dongtai_web/threshold/get_config_setting_detail.py
  dongtai_web/threshold/get_webhook_setting.py
  dongtai_web/threshold/tests.py
  dongtai_web/threshold/webhook_setting.py
  dongtai_web/threshold/webhook_type.py
  dongtai_web/urls.py
  dongtai_web/views/api_route_cover_rate.py
  dongtai_web/views/api_route_related_request.py
  dongtai_web/views/api_route_search.py
  dongtai_web/views/log_clear.py
  dongtai_web/views/log_delete.py
  dongtai_web/views/log_download.py
  dongtai_web/views/log_export.py
  dongtai_web/views/logs.py
  dongtai_web/views/new_project_query.py
  dongtai_web/views/vul_recheck.py
  dongtai_web/views/vul_recheck_v2.py
  dongtai_web/vul_recheck_payload/__init__.py
  dongtai_web/vul_recheck_payload/vul_recheck_payload.py
Labels: size/XXL

#1572 fix: type hint error
  dongtai_common/utils/init_schema.py
Labels: size/XS

#1573 fix: log filte
  dongtai_common/endpoint/__init__.py
Labels: size/XS

#1574 feat: add new patch
  dongtai_conf/patch/__init__.py
Labels: size/M

#1576 feat: cython parallel compilation
  setup.py
Labels: size/M

#1578 fix: project add error
  dongtai_web/views/project_add.py
Labels: size/XS

#1580 fix: project add error
  dongtai_web/views/project_add.py
Labels: size/XS

#1579 fix: validator not working in validate command and tag.
  dongtai_common/common/agent_command_check.py
  dongtai_conf/settings.py
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/M

#1581 feat: update patch
  dongtai_conf/patch/__init__.py
Labels: size/L

#1582 feat: cut out vul list
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/L

#1585 Feat/celery project timestamp update
  dongtai_conf/celery.py
  dongtai_engine/plugins/project_time_update.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/api_route_handler.py
  dongtai_web/views/project_summary.py
Labels: size/M

#1588 fix: disable branch search.
  dongtai_common/engine/vul_engine.py
Labels: size/S

#1589 feat: change default strategy template when add strategy
  dongtai_web/views/strategys.py
Labels: size/XS

#1592 feat: project version timestamp update.
  dongtai_web/views/project_summary.py
Labels: size/XS

#1590 fix: vul status error in heartbeat
  dongtai_protocol/report/handler/heartbeat_handler.py
Labels: size/S

#1594 pref: improve projects performance
  dongtai_web/views/projects.py
Labels: size/XS

#1596 fix: celery connection error
  dongtai_conf/celery.py
Labels: size/XS

#1597 pref: improve strategy types performance
  dongtai_web/views/strategys_type.py
Labels: size/XS

#1598 pref: improve hook rules performance
  dongtai_web/views/engine_hook_rules.py
Labels: size/XS

#1600 fix: update project status error
  dongtai_common/models/project.py
  dongtai_engine/plugins/project_status.py
Labels: size/S

#1608 fix: agent download template id.
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1610 feat: disable drf spectacular log
  dongtai_conf/settings.py
Labels: size/XS

#1613 feat: update 1.13.0 strategy.
  dongtai_engine/common/queryset.py
  static/data/go_full_policy.json
  static/data/go_policy.json
  static/data/java_full_policy.json
  static/data/java_policy.json
  static/data/python_full_policy.json
  static/data/python_policy.json
  static/data/vul_strategy.json
Labels: size/XXL

#1614 feat: update 1.13.0 params.
  static/data/java_params.json
Labels: size/L

#1615 feat: update 1.13.0 strategy.
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/M

#1616 feat: change init schema log level
  dongtai_common/utils/init_schema.py
Labels: size/XS

#1618 feat: update 1.13.0 strategy.
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/L

#1619 fix: api documents fix.
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/S

#1621 fix: add miss api vul_recheck_payload
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/urls.py
  dongtai_web/vul_recheck_payload/__init__.py
  dongtai_web/vul_recheck_payload/vul_recheck_payload.py
Labels: size/L

#1620 fix: schema error
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/profile.py
Labels: size/S

#1622 fix: new graph check node exists.
  dongtai_common/engine/vul_engine.py
Labels: size/XS

#1624 docs: change schema to chinese
  dongtai_protocol/views/agent_download.py
  dongtai_protocol/views/health_oss.py
  dongtai_protocol/views/hook_profiles.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggregation/aggregation_del.py
  dongtai_web/aggregation/aggregation_project_del.py
  dongtai_web/enum/hook_rules.py
  dongtai_web/header_vul/base.py
  dongtai_web/views/project_summary.py
  dongtai_web/views/sensitive_info_rule.py
  dongtai_web/views/user_detail.py
  dongtai_web/views/user_token.py
Labels: size/L

#1627 fix: logstash prase json error.
  dongtai_common/engine/vul_engine.py
  dongtai_protocol/report/log_service.py
Labels: size/S

#1628 fix: logstash prase json error.
  dongtai_protocol/report/log_service.py
Labels: size/XS

#1629 fix: logstash prase json error.
  dongtai_common/models/vulnerablity.py
Labels: size/S

#1631 fix: source method repeated.
  dongtai_common/engine/vul_engine.py
Labels: size/XS

#1626 docs: change schema to chinese
  dongtai_common/endpoint/__init__.py
  dongtai_protocol/views/agent_download.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggregation/aggregation_del.py
  dongtai_web/aggregation/aggregation_project_del.py
  dongtai_web/views/sensitive_info_rule.py
  dongtai_web/vul_recheck_payload/vul_recheck_payload.py
Labels: size/M

#1633 fix/logstash_parse_json_error
  dongtai_protocol/report/log_service.py
Labels: size/XS

#1634 docs: fix schema error
  dongtai_common/models/project.py
  dongtai_web/views/details_id.py
  dongtai_web/views/new_project_query.py
  dongtai_web/views/projects.py
Labels: size/S

#1639 fix: fix log filter
  dongtai_common/endpoint/__init__.py
Labels: size/XS

#1640 chore: modify github workflow tests
  .github/workflows/nightly.yaml
  .github/workflows/teststate.yml
  test/debug/management/commands/check_schema.py
Labels: size/L

#1642 refactor: use networkit rewrite vul scan.
  dongtai_common/engine/tests/mockdata/propagator_range-remove_unsafe_string-builder-delete.json
  dongtai_common/engine/tests/mockdata/range-subset_safe_string_builder_substring_start2.json
  dongtai_common/engine/tests/mockdata/reflection-injection_safe_for-name.json
  dongtai_common/engine/tests/mockdata/ssrf_safe_java-net-url-connection-param.json
  dongtai_common/engine/tests/mockdata/ssrf_unsafe_java-net-url-connection.json
  dongtai_common/engine/tests/test_vul_engine_search.py
  dongtai_common/engine/vul_engine.py
Labels: size/XXL

#1645 fix: that a context manager cant be used with FileResponse.
  dongtai_protocol/views/agent_download.py
  dongtai_protocol/views/engine_download.py
  dongtai_web/scaupload/views.py
  dongtai_web/views/agent_download.py
Labels: size/M

#1646 refactor: change file place.
  dongtai_web/dongtai_sca/scan/cwe.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XXL

#1647 chore: update batect
  batect
  batect.cmd
Labels: size/S

#1648 fix: ruff check
  dongtai_common/models/user.py
  dongtai_engine/preheat.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/views/scas.py
Labels: size/S

#1650 feat: change auth to use projects
  dongtai_common/endpoint/__init__.py
  dongtai_common/models/user.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/aggregation/aggregation_del.py
  dongtai_web/aggregation/aggregation_project_del.py
  dongtai_web/base/project_version.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
  dongtai_web/header_vul/base.py
  dongtai_web/views/agent_start.py
  dongtai_web/views/agent_stop.py
  dongtai_web/views/agents_v2.py
  dongtai_web/views/project_add.py
  dongtai_web/views/project_delete.py
  dongtai_web/views/project_detail.py
  dongtai_web/views/project_engines.py
  dongtai_web/views/project_summary.py
  dongtai_web/views/project_version_add.py
  dongtai_web/views/project_version_list.py
  dongtai_web/views/project_version_update.py
  dongtai_web/views/projects.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
  dongtai_web/views/user_token.py
  dongtai_web/views/vul_count_for_plugin.py
  dongtai_web/views/vul_details.py
  dongtai_web/views/vul_list_for_plugin.py
  dongtai_web/views/vul_status.py
Labels: size/L

#1651 chore: update cython
  .github/workflows/nightly.yaml
Labels: size/XS

#1652 chore: add workflow dispatch for nightly
  .github/workflows/nightly.yaml
Labels: size/XS

#1653 Feat/use migrations
  .gitignore
  deploy/docker/version.sql
  dongtai_common/migrations/0001_initial.py
  dongtai_common/migrations/__init__.py
  dongtai_common/models/agent.py
  dongtai_common/models/agent_config.py
  dongtai_common/models/assetv2.py
  dongtai_common/models/dast_integration.py
  dongtai_common/models/department.py
  dongtai_common/models/hook_strategy.py
  dongtai_common/models/hook_type.py
  dongtai_common/models/iast_vul_log.py
  dongtai_common/models/message.py
  dongtai_common/models/project.py
  dongtai_common/models/project_version.py
  dongtai_common/models/sensitive_info.py
  dongtai_common/models/strategy.py
  dongtai_common/models/version_control.py
  dongtai_common/models/vul_recheck_payload.py
  dongtai_common/utils/db.py
  dongtai_common/utils/settings.py
Labels: size/XXL

#1654 fix: cython build error
  dongtai_common/common/utils/__init__.py
  dongtai_common/endpoint/__init__.py
  pyproject.toml
  test/testcase.py
Labels: size/M

#1656 feat: use migrations.
  deploy/docker/version.sql
Labels: size/L

#1659 fix: department token error
  dongtai_web/views/user_token.py
Labels: size/XS

#1660 feat: change agent register.
  dongtai_common/engine/vul_engine.py
  dongtai_protocol/views/agent_config.py
  dongtai_protocol/views/agent_register.py
  test/apiserver/test_agent_method_pool.py
  test/apiserver/test_agent_normal_vulnv2.py
Labels: size/M

#1661 feat: add project permission model
  .github/workflows/nightly.yaml
  .github/workflows/teststate.yml
  dongtai_common/migrations/0002_auto_20230726_1433.py
  dongtai_common/models/__init__.py
  dongtai_common/models/project.py
  dongtai_common/models/project_group.py
  dongtai_common/models/role.py
  dongtai_common/models/user.py
Labels: size/L

#1664 feat: change role model name
  dongtai_common/migrations/0002_auto_20230726_1433.py
  dongtai_common/models/iast_role.py
  dongtai_common/models/user.py
Labels: size/S

#1666 feat: add request type
  dongtai_common/utils/request_type.py
  dongtai_protocol/views/agent_register.py
  dongtai_protocol/views/engine_download.py
  dongtai_protocol/views/properties.py
  dongtai_protocol/views/startuptime.py
  dongtai_web/systemmonitor/project_warning.py
Labels: size/S

#1667 feat: change agent register.
  dongtai_common/common/utils/__init__.py
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#1668 feat: modify project group model
  dongtai_common/common/utils/__init__.py
  dongtai_common/models/project_group.py
Labels: size/XS

#1669 feat: add m2m fields.
  dongtai_common/models/project.py
  dongtai_common/models/user.py
Labels: size/XS

#1671 feat: change auth to use projects.
  dongtai_common/models/project.py
Labels: size/XS

#1673 chore: change Cython build file
  dongtai_common/utils/user.py
  setup.py
Labels: size/S

#1674 feat: add deleted field to user model
  dongtai_common/migrations/0003_auto_20230728_1444.py
  dongtai_common/models/user.py
Labels: size/M

#1672 feat: remove unused serializer
  dongtai_web/serializers/department.py
  dongtai_web/serializers/user.py
Labels: size/M

#1675 feat: network scan detect multi path.
  dongtai_common/engine/vul_engine.py
  dongtai_engine/tasks.py
  test/apiserver/test_agent_normal_vuln_scan_networkv2.py
  test/integration/mockdata/2individualpath.json
  test/integration/mockdata/2pathdifferentsourcev1.json
  test/integration/mockdata/2pathdifferentsourcev2.json
Labels: size/XXL

#1677 fix: fix type summary in project_summary.
  dongtai_web/views/project_summary.py
Labels: size/XS

#1679 fix: user model get_projects method
  dongtai_common/models/user.py
Labels: size/XS

#1678 feat: add project group name field in project list api
  dongtai_web/serializers/project.py
  dongtai_web/views/projects.py
Labels: size/S

#1680 fix: user model get_projects method
  dongtai_common/models/user.py
Labels: size/XS

#1682 fix: disk rate parse .
  dongtai_web/views/agents_v2.py
Labels: size/XS

#1685 feat: add chinese sca
  dongtai_common/serializers/assetvulv2.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M
