Repository HXSecurity/DongTai, pull requests merged in 2023-09, with the labels that each got.

#1777 feat: add custom tag
  dongtai_conf/settings.py
Labels: size/S

#1778 feat: change hook strategy length limit.
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/XS

#1779 Feat/add new topo table
  dongtai_common/migrations/0020_iastagentrequestchainstopograph_iastagentrequestchainstopographvec_iastagentrequestchainstotalprojec.py
  dongtai_common/models/request_chains.py
Labels: size/L

#1781 deps: add pandas dependance
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/L

#1782 feat: custom max page size
  dongtai_common/endpoint/__init__.py
Labels: size/XS

#1783 feat: modify notify
  dongtai_common/migrations/0021_iastwebhooklog.py
  dongtai_common/models/__init__.py
  dongtai_common/models/notify_log.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_web/dongtai_sca/scan/tasks.py
  dongtai_web/vul_log/vul_log.py
Labels: size/M

#1784 refactor: vul details api parse_graph
  dongtai_web/views/vul_details.py
Labels: size/XS

#1786 feat: add replay header
  dongtai_common/models/iast_vul_log.py
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/S

#1789 feat: modify hook strategy update logic
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_web/serializers/hook_strategy.py
  dongtai_web/serializers/hook_type_strategy.py
  dongtai_web/serializers/strategy.py
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/views/engine_hook_rule_modify.py
  dongtai_web/views/engine_hook_rule_status.py
  dongtai_web/views/strategy_delete.py
  dongtai_web/views/strategy_modified.py
Labels: size/L

#1797 Feat/add project token
  dongtai_common/common/utils/__init__.py
  dongtai_common/migrations/0022_iastproject_token.py
  dongtai_common/models/project.py
  dongtai_common/models/user.py
  dongtai_conf/settings.py
  dongtai_protocol/views/agent_register.py
  dongtai_web/urls.py
  dongtai_web/views/project_token.py
Labels: size/L

#1795 feat: heartbeat use celery task
  dongtai_protocol/report/handler/heartbeat_handler.py
Labels: size/S

#1796 fix: save vul did not save uri
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/XS

#1798 feat: add project token
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#1799 feat: add new migration
  dongtai_common/migrations/0023_auto_20230912_1211.py
  dongtai_common/models/request_chains.py
Labels: size/S

#1780 fix: memory reduce.
  dongtai_common/engine/vul_engine.py
Labels: size/XS

#1800 dep: add new migration
  Pipfile
  Pipfile.lock
Labels: size/XS

#1801 fix: modify rule value
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/XS

#1802 fix: set language
  static/i18n/views/setlang.py
Labels: size/XS

#1803 fix: modify rule value
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/XS

#1804 deps: add more itertools
  Pipfile
  Pipfile.lock
Labels: size/XS

#1805 feat/project token p2
  dongtai_common/common/utils/__init__.py
  dongtai_common/endpoint/__init__.py
  dongtai_conf/settings.py
  dongtai_protocol/views/agent_download.py
Labels: size/S

#1806 feat/remove no risk level
  dongtai_web/views/utils/commonstats.py
Labels: size/XS

#1807 feat/project token p2
  dongtai_web/views/project_token.py
Labels: size/XS

#1808 fix: heartbeat task error
  dongtai_conf/celery.py
Labels: size/XS

#1811 feat: sensitive info rule add system type
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_common/migrations/0024_iastsensitiveinforule_system_type.py
  dongtai_common/models/sensitive_info.py
  dongtai_web/views/sensitive_info_rule.py
Labels: size/M

#1810 fix: heartbeat task error
  dongtai_protocol/report/handler/heartbeat_handler.py
Labels: size/XS

#1813 fix: vul status const error
  dongtai_common/utils/const.py
Labels: size/XS

#1812 fix: change to directed graph.
  dongtai_common/engine/vul_engine.py
Labels: size/XS

#1814 Feat/add constrain in vec
  dongtai_common/migrations/0025_alter_iastagentrequestchainstopographvec_unique_together.py
  dongtai_common/models/request_chains.py
Labels: size/S

#1815 Feat/add doc
  dongtai_common/models/asset_vul_v2.py
  dongtai_common/serializers/assetv2.py
  dongtai_common/serializers/assetvulv2.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
  dongtai_web/serializers/aggregation.py
  dongtai_web/views/project_version_list.py
  dongtai_web/views/projects.py
  dongtai_web/views/vul_details.py
Labels: size/L

#1816 feat: update new strategy.
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/XXL

#1817 fix:project_agent_download_token
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1818 feat: update new strategy.
  static/data/java_full_policy.json
  static/data/java_policy.json
  static/data/vul_strategy.json
Labels: size/XXL

#1828 fix: load hook strategy
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_web/views/engine_method_pool_search.py
Labels: size/XS

#1829 feat: sensitive info pattern use text
  dongtai_common/migrations/0026_auto_20230918_1413.py
  dongtai_common/models/sensitive_info.py
Labels: size/L

#1830 fix: agent download.
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1831 fix: patch
  dongtai_conf/patch/__init__.py
Labels: size/XS

#1832 feat: add new permission.
  dongtai_common/migrations/0026_auto_20230919_1233.py
Labels: size/L

#1833 feat: add new permission.
  dongtai_common/migrations/0027_auto_20230919_1233.py
Labels: size/XS

#1834 fix: load hook strategy
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_common/migrations/0028_hookstrategy_modified.py
  dongtai_common/models/hook_strategy.py
  dongtai_web/views/engine_hook_rule_modify.py
  dongtai_web/views/engine_hook_rule_status.py
Labels: size/M

#1835 fix: modify sensitive info rule status
  dongtai_web/views/sensitive_info_rule.py
Labels: size/S

#1836 fix: patch log
  dongtai_conf/patch/__init__.py
Labels: size/XS

#1837 pref: sensitive info rule list
  dongtai_web/views/sensitive_info_rule.py
Labels: size/XS

#1841 feat: improve patch type hint
  dongtai_conf/patch/__init__.py
Labels: size/XS

#1839 feat: modify user field
  dongtai_common/migrations/0029_user_totp_secret.py
  dongtai_common/models/user.py
Labels: size/S

#1843 Feat/1.15.0 develop
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_common/migrations/0026_auto_20230918_1413.py
  dongtai_common/migrations/0027_auto_20230919_1233.py
  dongtai_common/migrations/0028_hookstrategy_modified.py
  dongtai_common/models/hook_strategy.py
  dongtai_common/models/sensitive_info.py
  dongtai_conf/patch/__init__.py
  dongtai_protocol/views/agent_download.py
  dongtai_web/views/engine_hook_rule_modify.py
  dongtai_web/views/engine_hook_rule_status.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/sensitive_info_rule.py
Labels: size/L

#1844 Beta
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_common/migrations/0026_auto_20230918_1413.py
  dongtai_common/migrations/0027_auto_20230919_1233.py
  dongtai_common/migrations/0028_hookstrategy_modified.py
  dongtai_common/models/hook_strategy.py
  dongtai_common/models/sensitive_info.py
  dongtai_conf/patch/__init__.py
  dongtai_protocol/views/agent_download.py
  dongtai_web/views/engine_hook_rule_modify.py
  dongtai_web/views/engine_hook_rule_status.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/sensitive_info_rule.py
Labels: size/L

#1840 feat: remove login lock
  dongtai_web/views/user_login.py
Labels: size/S

#1838 feat:add agent version api.
  dongtai_web/urls.py
  dongtai_web/views/agents_v2.py
Labels: size/S

#1842 feat/project_type_summary
  dongtai_web/urls.py
  dongtai_web/views/project_summary.py
  dongtai_web/views/project_type_summary_list.py
  dongtai_web/views/utils/commonstats.py
Labels: size/L

#1846 deps: add pyotp dep
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/M

#1845 feat: add project status change notify
  dongtai_common/models/project.py
  dongtai_engine/plugins/project_status.py
  dongtai_web/views/engine_hook_rule_add.py
Labels: size/M

#1847 fix: percentage zero error.
  dongtai_web/views/utils/commonstats.py
Labels: size/XS

#1849 fix: zero divide
  dongtai_web/views/utils/commonstats.py
Labels: size/XS

#1848 fix: project current version auth fix.
  dongtai_web/views/project_search.py
  dongtai_web/views/project_version_current.py
  dongtai_web/views/vul_summary.py
  dongtai_web/views/vul_summary_project.py
  dongtai_web/views/vul_summary_type.py
  dongtai_web/views/vuls.py
Labels: size/S

#1853 feat: add request topo models.
  dongtai_common/migrations/0030_iastagentblackrule_iastagentblackruledetail_iastagentrequestchainstopototalprojectversiongraph_iasta.py
  dongtai_common/migrations/0031_auto_20230926_1510.py
  dongtai_common/models/request_chains.py
Labels: size/L

#1854 feat: project type summary list.
  dongtai_web/views/project_type_summary_list.py
Labels: size/XS

#1856 feat: modify user info api
  dongtai_web/views/user_info.py
Labels: size/XS
