Repository HXSecurity/DongTai, pull requests merged in 2023-02, with the labels that each got.

#1212 feat/project-template-p5
  dongtai_protocol/views/agent_configv2.py
Labels: size/XS

#1213 feat(projecttemplate): fix none safe.
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#1214 feat/project-template-p6
  dongtai_protocol/views/agent_download.py
Labels: size/S

#1216 Update base.py
  dongtai_web/projecttemplate/base.py
Labels: size/XS

#1217 feat/project-template-p7
  dongtai_common/common/utils/__init__.py
  dongtai_common/models/agent.py
  dongtai_common/models/api_route.py
  dongtai_common/models/project.py
  dongtai_common/models/user.py
  dongtai_common/models/vulnerablity.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/api_route_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/agent_register.py
Labels: size/L

#1218 feat/project-template-p8
  deploy/commands/management/commands/updatedepartmenttoken.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/S

#1220 feat/project-template-p10
  dongtai_common/models/asset_vul.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/S

#1221 feat/project-template-p11
  dongtai_protocol/report/handler/hardencode_vul_handler.py
Labels: size/XS

#1222 feat: No user ID is required when querying project versions
  dongtai_web/base/project_version.py
  dongtai_web/views/api_route_cover_rate.py
  dongtai_web/views/api_route_related_request.py
  dongtai_web/views/api_route_search.py
  dongtai_web/views/project_detail.py
  dongtai_web/views/project_summary.py
  dongtai_web/views/projects.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
  dongtai_web/views/vul_summary.py
  dongtai_web/views/vul_summary_project.py
  dongtai_web/views/vul_summary_type.py
  dongtai_web/views/vuls.py
Labels: size/M

#1225 feat : sca new query after using department.
  dongtai_common/models/user.py
  dongtai_conf/settings.py
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/dongtai_sca/views/package_vul.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
Labels: size/L

#1223 feat: Vulnerability acquisition page summary added language
  deploy/docker-compose/dtctl
  dongtai_common/models/strategy_user.py
  dongtai_common/models/user.py
  dongtai_common/models/vulnerablity.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_protocol/report/handler/report_handler_interface.py
  dongtai_web/aggr_vul/app_vul_summary.py
  dongtai_web/base/project_version.py
  dongtai_web/views/agents_v2.py
  dongtai_web/views/project_add.py
  dongtai_web/views/project_delete.py
  dongtai_web/views/project_detail.py
  dongtai_web/views/project_engines.py
  dongtai_web/views/project_summary.py
  dongtai_web/views/project_version_add.py
  dongtai_web/views/project_version_list.py
  dongtai_web/views/project_version_update.py
  dongtai_web/views/projects.py
  dongtai_web/views/user_token.py
  test/iast/views/test_vul_summary.py
Labels: size/L

#1226 feat: new sca select query change.
  dongtai_common/endpoint/__init__.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/dongtai_sca/common/sca_vul.py
  dongtai_web/dongtai_sca/views/package_vul.py
  dongtai_web/views/api_route_cover_rate.py
  dongtai_web/views/api_route_search.py
Labels: size/M

#1228 fix: fix sca department id change .
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1229 fix: fix sca department id change .
  dongtai_common/endpoint/__init__.py
  dongtai_web/views/vul_list_for_plugin.py
Labels: size/XS

#1231 fix: fix api route change .
  dongtai_web/base/project_version.py
  dongtai_web/views/api_route_cover_rate.py
  dongtai_web/views/api_route_search.py
Labels: size/S

#1235 fix(pr): Update Vulnerability Queries, add department_id
  dongtai_common/models/vulnerablity.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_web/aggr_vul/app_vul_list.py
  test/iast/views/test_vul_summary.py
Labels: size/S

#1236 fix: fix sca summary es query.
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#1238 fix: fix sca summary es query.
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#1239 fix: fix sca summary es query.
  dongtai_web/aggr_vul/aggr_vul_list.py
Labels: size/XS

#1242 fix: fix sca summary es query.
  dongtai_web/views/user_token.py
Labels: size/XS

#1243 fix: fix sca summary es query.
  dongtai_common/common/utils/__init__.py
  dongtai_web/views/user_token.py
Labels: size/XS

#1244 fix: fix admin auth.
  dongtai_common/models/user.py
Labels: size/XS

#1245 fix: fix vul details.
  dongtai_web/views/vul_details.py
Labels: size/XS

#1250 fix: scan_strategys.
  dongtai_web/views/scan_strategys.py
  dongtai_web/views/strategys_list.py
Labels: size/S

#1251 fix: scan_strategys.
  dongtai_common/endpoint/__init__.py
  dongtai_web/projecttemplate/base.py
  dongtai_web/views/sensitive_info_rule.py
Labels: size/S

#1253 fix: add init
  dongtai_web/views/sensitive_info_rule.py
Labels: size/XS

#1254 fix: auth.
  dongtai_common/endpoint/__init__.py
  dongtai_web/projecttemplate/base.py
Labels: size/S

#1255 fix: asset query.
  dongtai_common/endpoint/__init__.py
Labels: size/XS

#1257 fix: bugfix scan project add change .
  dongtai_web/views/project_add.py
  dongtai_web/views/scan_strategys.py
Labels: size/S

#1259 feat: new strategy 1.9.2 .
  static/data/go_full_policy.json
  static/data/go_policy.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/python_full_policy.json
  static/data/python_policy.json
  static/data/vul_strategy.json
Labels: size/XL

#1260 feat: strategy 1.9.2 .
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
Labels: size/XL

#1258 feat: Update configurations such as vulnerability verification
  dongtai_engine/plugins/data_clean.py
  dongtai_web/aggregation/aggregation_del.py
  dongtai_web/views/log_download.py
  dongtai_web/views/sensitive_info_rule.py
  dongtai_web/views/vul_recheck_v2.py
  dongtai_web/views/vul_status.py
  dongtai_web/vul_log/vul_log.py
Labels: size/M

#1262 fix: relation
  deploy/commands/management/commands/updateifdepartmentisolation.py
  dongtai_common/endpoint/__init__.py
  dongtai_common/models/project.py
  dongtai_common/models/user.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_protocol/views/agent_register.py
  dongtai_web/aggregation/aggregation_common.py
  dongtai_web/aggregation/aggregation_del.py
  dongtai_web/base/project_version.py
  dongtai_web/serializers/sca.py
  dongtai_web/views/project_add.py
  dongtai_web/views/project_detail.py
  dongtai_web/views/project_version_delete.py
  test/apiserver/test_agent_hardencode_vuln.py
Labels: size/XL

#1265 feat: new plugin api.
  dongtai_web/views/vul_count_for_plugin.py
  dongtai_web/views/vul_list_for_plugin.py
Labels: size/S

#1267 fix: field limit in projecttemplate
  .github/workflows/teststate.yml
  dongtai_common/common/utils/__init__.py
  dongtai_common/endpoint/__init__.py
  dongtai_common/engine/compatibility.py
  dongtai_common/models/aql_info.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/views/agent_register.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggregation/aggregation_common.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/asset_projects.py
  dongtai_web/projecttemplate/base.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/vul_details.py
  dongtai_web/views/vul_list_for_plugin.py
  dongtai_web/views/vul_status.py
  dongtai_web/views/vul_summary_project.py
  dongtai_web/views/vul_summary_type.py
Labels: size/XL

#1268 deps: unlock types deps version.
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/M

#1269 fix: regex validation in groups limitation remove.
  dongtai_engine/plugins/strategy_sensitive.py
  dongtai_web/views/sensitive_info_rule.py
Labels: size/M

#1271 ci: add bandit and flake8.
  .github/workflows/teststate.yml
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/agent_download.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/utils.py
Labels: size/M

#1273 ci: add bandit and flake8.
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1272 ci: add bandit and flake8.
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1274 ci: add bandit and flake8.
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1270 fix: README-zh.md
  README-zh.md
Labels: size/XS

#1275 fix: agent status ids update.
  dongtai_web/views/agent_start.py
  dongtai_web/views/agent_stop.py
Labels: size/XS

#1276 fix: agent status ids update.
  dongtai_web/views/agent_start.py
  dongtai_web/views/agent_stop.py
Labels: size/XS

#1277 fix: query optimise.
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/S

#1278 fix: vul accepet
  dongtai_protocol/report/handler/hardencode_vul_handler.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
Labels: size/XS

#1279 fix: vul accepet
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#1280 fix: strategy update
  static/data/go_full_policy.json
  static/data/go_policy.json
  static/data/java_full_policy.json
  static/data/java_policy.json
  static/data/python_full_policy.json
  static/data/python_policy.json
  static/data/vul_strategy.json
Labels: size/XL

#1283 fix: agent list time filter .
  dongtai_web/views/agents_v2.py
Labels: size/S

#1284 Fix/typing check fix
  .github/workflows/teststate.yml
  Pipfile
  Pipfile.lock
  dongtai_common/common/utils/__init__.py
  dongtai_common/models/user.py
  dongtai_protocol/utils.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/utils.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/vul_request_replay.py
  requirements.txt
Labels: size/M

#1287 fix: project template update .
  dongtai_web/projecttemplate/base.py
Labels: size/XS

#1286 Feat/new project vul del api
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggregation/aggregation_project_del.py
  dongtai_web/urls.py
Labels: size/M

#1288 fix: narmal vul upload fix
  dongtai_protocol/report/handler/narmal_vul_handler.py
Labels: size/XS

#1289 fix: log delete in.
  dongtai_web/views/log_delete.py
Labels: size/S

#1290 fix: normal vul handler.
  dongtai_protocol/report/handler/narmal_vul_handler.py
Labels: size/M

#1291 fix: project del.
  dongtai_web/aggregation/aggregation_project_del.py
Labels: size/XS

#1292 fix: hook rule goblal.
  dongtai_protocol/views/hook_profilesv2.py
  dongtai_web/views/engine_hook_rule_modify.py
  dongtai_web/views/engine_hook_rule_type_disable.py
  dongtai_web/views/engine_hook_rule_type_enable.py
  dongtai_web/views/engine_hook_rules.py
Labels: size/S

#1293 fix: hook rule goblal.
  dongtai_web/views/engine_hook_rule_status.py
Labels: size/M

#1294 fix: user logout delete session.
  dongtai_web/views/user_logout.py
Labels: size/XS

#1296 build(cache): add cache .
  setup.py
Labels: size/XS

#1297 fix: hook rule status change .
  dongtai_web/projecttemplate/base.py
  dongtai_web/views/engine_hook_rule_status.py
Labels: size/XS
