Repository HXSecurity/DongTai, pull requests merged in 2023-06, with the labels that each got.

#1476 Feat/new sca impl scan
  Dockerfile
  dongtai_common/models/asset_vul_v2.py
  dongtai_common/models/assetv2.py
  dongtai_protocol/report/handler/sca_handler.py
  dongtai_web/dongtai_sca/common/dataclass.py
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagedetail.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
Labels: size/XL

#1477 feat: new sca impl.
  Dockerfile
Labels: size/XS

#1478 feat: new sca impl.
  dongtai_common/models/assetv2.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/views/newpackagevuldetail.py
Labels: size/S

#1479 feat: new sca impl.
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
Labels: size/S

#1480 feat: new sca impl api fix .
  Pipfile
  Pipfile.lock
  dongtai_common/models/assetv2.py
  dongtai_web/dongtai_sca/common/dataclass.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackage.py
  requirements.txt
Labels: size/M

#1481 feat: new sca impl api add field.
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/views/newpackagedetail.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
Labels: size/M

#1483 feat: new sca impl api add field.
  dongtai_web/dongtai_sca/views/newpackagedetail.py
Labels: size/XS

#1484 fix: doc fix.
  dongtai_web/dongtai_sca/views/newpackagevuls.py
Labels: size/XS

#1485 fix: project time stamp update task.
  dongtai_conf/celery.py
Labels: size/XS

#1482 fix: old scan util type check.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1486 feat: new sca impl api add field.
  dongtai_common/models/asset_vul_v2.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1487 feat: new sca impl api fix version.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#1490 fix: sca summary.
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
Labels: size/L

#1491 fix: type infer in license.
  dongtai_conf/settings.py
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
Labels: size/M

#1492 fix: type infer in license.
  dongtai_web/dongtai_sca/views/newpackage.py
Labels: size/XS

#1493 fix: type infer in license.
  dongtai_web/dongtai_sca/views/newpackage.py
Labels: size/S

#1495 Feat/add route cover count
  dongtai_web/views/api_route_cover_rate.py
Labels: size/M

#1496 feat: vul status wont change in the final state.
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_web/views/vul_recheck_v2.py
Labels: size/S

#1497 feat: add rate limit
  dongtai_conf/settings.py
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#1498 fix/dast_vul_filter-failed
  dongtai_web/dast/page.py
Labels: size/XS

#1499 fix/dast_vul_filter-failed
  dongtai_web/dast/page.py
Labels: size/XS

#1501 fix: fix sca scan when package_publish_time empty.
  .github/deploy/deploy-dongtai-server-test.yml
  dongtai_web/dast/page.py
  dongtai_web/dongtai_sca/common/dataclass.py
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#1502 fix: summary type in sca.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1503 fix: new asset risk level.
  dongtai_common/models/asset_vul_v2.py
  dongtai_common/models/assetv2.py
  dongtai_common/serializers/__init__.py
  dongtai_common/serializers/assetv2.py
  dongtai_common/serializers/assetvulv2.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagedetail.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
  dongtai_web/dongtai_sca/views/newpackagevuldetail.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
Labels: size/L

#1504 fix: new asset risk summary.
  dongtai_common/models/assetv2.py
  dongtai_common/serializers/assetv2.py
  dongtai_common/serializers/assetvulv2.py
  dongtai_web/dongtai_sca/views/newpackage.py
Labels: size/S

#1505 fix: new asset risk summary.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1506 fix: remove update all status.
  dongtai_web/threshold/agent_core_status.py
Labels: size/S

#1507 feat: add new tag.
  dongtai_conf/settings.py
Labels: size/XS

#1509 feat: add new package vul level api.
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/views/newpackagevullevel.py
Labels: size/M

#1510 feat: add new package vul level api.
  dongtai_web/dongtai_sca/urls.py
Labels: size/XS

#1508 feat: add new strategy.
  static/data/go_full_policy.json
  static/data/go_hooktype.json
  static/data/go_policy.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_full_policy.json
  static/data/python_hooktype.json
  static/data/python_policy.json
  static/data/vul_strategy.json
Labels: size/XXL

#1511 fix: sca scan_data transform.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#1513 fix: vul_level match count.
  dongtai_web/dongtai_sca/scan/tests.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/S

#1515 feat: project vul filter by uri.
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/serializers/aggregation.py
Labels: size/XS

#1518 fix: sca scan typing.
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/XS

#1517 Development/add silk as profiler p2
  dongtai_conf/urls.py
Labels: size/XS

#1519 feat: mirgate api route gather to celery task.
  deploy/docker/entrypoint.sh
  dongtai_conf/celery.py
  dongtai_protocol/report/handler/api_route_handler.py
Labels: size/L

#1520 feat: hook profile download queries optimise.
  dongtai_protocol/views/hook_profilesv2.py
Labels: size/M

#1521 fix: agent download replace jar to zip.
  Dockerfile
  dongtai_conf/settings.py
  dongtai_protocol/views/agent_download.py
Labels: size/XS

#1522 fix: scan utils typing check.
  .gitignore
  dongtai_web/dongtai_sca/common/dataclass.py
  dongtai_web/dongtai_sca/scan/utils.py
Labels: size/M

#1523 fix: scan utils typing check.
  setup.py
Labels: size/XS

#1524 fix: scan utils typing check.
  .github/workflows/teststate.yml
Labels: size/XS

#1525 feat: add new strategy .
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/XXL

#1526 fix stack_recognize white list not working
  dongtai_common/utils/stack_recognize.py
Labels: size/XS

#1527 feat: add new strategy .
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/M

#1528 feat: add new startegy 1.12.0
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/M

#1529 feat: package relative version query change.
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
Labels: size/XS

#1530 feat: package relative version query change.
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
Labels: size/XS

#1531 feat: package relative project query change.
  dongtai_web/dongtai_sca/views/newpackageprojects.py
Labels: size/M

#1532 change query in sca relation query
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
Labels: size/XS

#1533 build: add deps
  Dockerfile
Labels: size/XS

#1541 feat: update new strategy.
  static/data/java_full_policy.json
  static/data/java_policy.json
Labels: size/M

#1544 feat: add project id and project version id in project add api.
  dongtai_protocol/api_schema.py
  dongtai_protocol/views/agent_download.py
  dongtai_web/views/project_add.py
Labels: size/L

#1545 fix: api route parameter not correct record with multi method case.
  .github/workflows/teststate.yml
  dongtai_conf/celery.py
  dongtai_protocol/report/handler/api_route_handler.py
  dongtai_protocol/tests.py
  test/apiserver/test_agent_apiroute_parameter.py
Labels: size/M

#1548 Revert "feat/new_api_route_upload"
  dongtai_common/models/api_route_v2.py
  dongtai_common/utils/const.py
  dongtai_conf/celery.py
  dongtai_protocol/report/__init__.py
  dongtai_protocol/report/handler/api_route_v2_handler.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  test/apiserver/test_agent_apiroute_v2.py
  test/integration/mockdata/api-report.json
Labels: size/L

#1551 fix: fix heartbeat handler save fail
  dongtai_protocol/report/handler/heartbeat_handler.py
  test/apiserver/test_agent_heartbeat.py
Labels: size/M

#1552 fix: remove not reliable api data.
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#1554 feat: add project status update task
  dongtai_common/models/project.py
  dongtai_conf/celery.py
  dongtai_engine/plugins/project_status.py
  dongtai_web/apps.py
  dongtai_web/serializers/project.py
Labels: size/L

#1556 feat: add project stauts filter
  dongtai_web/views/projects.py
Labels: size/M

#1560 feat: add project exclude vul status filter
  dongtai_web/serializers/project.py
  dongtai_web/views/projects.py
Labels: size/M

#1561 feat: remove some vul status
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_web/views/vul_recheck_v2.py
  test/core/tasks.py
Labels: size/M
