Repository HXSecurity/DongTai, pull requests merged in 2023-08, with the labels that each got.

#1686 feat: remove outdate api
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_common/engine/compatibility.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_protocol/views/except_action.py
  dongtai_web/aggr_vul/aggr_vul_list.py
  dongtai_web/aggr_vul/aggr_vul_summary.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/apps.py
  dongtai_web/base/agent.py
  dongtai_web/urls.py
  dongtai_web/views/sca_summary.py
  dongtai_web/views/scas.py
  dongtai_web/views/sensitive_info_rule.py
  dongtai_web/views/strategys_type.py
  dongtai_web/vul_recheck_payload/vul_recheck_payload.py
Labels: size/XXL

#1687 Feat/project metadata
  dongtai_common/migrations/0005_iastprojectmetadata.py
  dongtai_common/models/__init__.py
  dongtai_common/models/project_metadata.py
Labels: size/M

#1688 feat: add report validated sink config
  dongtai_protocol/views/agent_configv2.py
  dongtai_web/common.py
  test/apiserver/test_agent_config.py
Labels: size/M

#1691 fix: migration error
  dongtai_common/migrations/0002_auto_20230726_1433.py
Labels: size/XS

#1692 feat:add patch point.
  dongtai_common/permissions/__init__.py
Labels: size/S

#1693 feat: add hook strategt type in createion.
  dongtai_web/serializers/hook_strategy.py
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/M

#1684 chore: add rate limit to schemathesis
  .github/workflows/nightly.yaml
  .github/workflows/teststate.yml
Labels: size/XS

#1694 feat: add unique constraint to name field
  dongtai_common/migrations/0006_auto_20230803_1407.py
  dongtai_common/models/iast_role.py
  dongtai_common/models/project_group.py
Labels: size/M

#1696 feat: user login add is active field.
  dongtai_web/views/user_login.py
Labels: size/XS

#1695 pref: improve projects pref
  dongtai_web/serializers/project.py
  dongtai_web/views/projects.py
Labels: size/S

#1698 fix: agent register remove department.
  dongtai_protocol/views/agent_register.py
Labels: size/XS

#1699 fix: now its show the selected status vuls.
  dongtai_web/serializers/project.py
Labels: size/XS

#1701 feat: add project group name in project detail.
  dongtai_web/views/project_detail.py
Labels: size/XS

#1697 feat: add unique constraint
  dongtai_common/migrations/0007_auto_20230803_1810.py
  dongtai_common/models/project_group.py
Labels: size/M

#1702 feat: add unique to project metadata.
  dongtai_common/migrations/0007_alter_iastprojectmetadata_project.py
  dongtai_common/models/project_metadata.py
Labels: size/S

#1704 fix: remove department.
  dongtai_web/views/project_detail.py
Labels: size/XS

#1703 refactor: vul engine
  dongtai_common/engine/vul_engine.py
  dongtai_common/migrations/0007_alter_iastprojectmetadata_project.py
  dongtai_common/migrations/0008_alter_iastprojectmetadata_project.py
Labels: size/M

#1706 Feat/validate tag
  dongtai_engine/tasks.py
  test/apiserver/test_agent_normal_vuln_validated.py
  test/integration/mockdata/validated_method_pool.json
Labels: size/M

#1705 feat: project summary add project group name.
  dongtai_web/views/project_detail.py
  dongtai_web/views/project_summary.py
Labels: size/XS

#1707 fix: modify agent config api
  dongtai_protocol/views/agent_configv2.py
Labels: size/XS

#1710 fix: project vul_count with status filter.
  dongtai_web/serializers/project.py
Labels: size/XS

#1711 feat: agent register and heartbeat.
  dongtai_protocol/report/handler/heartbeat_handler.py
  dongtai_protocol/report/handler/report_handler_interface.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/XS

#1712 fix: permission fix in strategy create.
  dongtai_web/views/strategys.py
Labels: size/XS

#1713 fix: add hook rule field validate message.
  dongtai_common/common/agent_command_check.py
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/views/engine_hook_rule_modify.py
  test/apiserver/test_agent_base.py
  test/apiserver/test_agent_heartbeat.py
Labels: size/M

#1714 feat: allow inactive user login.
  dongtai_web/views/user_login.py
Labels: size/XS

#1709 pref: add index to db
  dongtai_common/migrations/0009_auto_20230808_1456.py
  dongtai_common/models/iast_role.py
  dongtai_common/models/project.py
  dongtai_common/models/project_group.py
  dongtai_common/models/user.py
Labels: size/M

#1717 feat: add role and group name limit.
  dongtai_common/migrations/0002_auto_20230726_1433.py
  dongtai_common/migrations/0010_auto_20230809_1838.py
  dongtai_common/models/iast_role.py
  dongtai_common/models/project_group.py
Labels: size/L

#1715 pref: improve package vul pref
  dongtai_common/serializers/assetvulv2.py
Labels: size/S

#1718 Feat/add project name limit
  dongtai_web/views/project_add.py
Labels: size/XS

#1720 feat:add user login massage
  dongtai_web/views/user_login.py
Labels: size/S

#1721 feat:add user login massage
  dongtai_web/views/user_login.py
Labels: size/XS

#1722 fix: test error
  dongtai_web/dongtai_sca/common/dataclass.py
  test/apiserver/test_agent_config.py
Labels: size/XS

#1719 fix: package vul error
  dongtai_common/serializers/assetvulv2.py
  dongtai_web/dongtai_sca/views/newpackagevuldetail.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
Labels: size/S

#1723 feat: project add create project user rel.
  dongtai_web/base/project_version.py
  dongtai_web/views/project_add.py
  dongtai_web/views/project_version_add.py
  dongtai_web/views/project_version_update.py
Labels: size/S

#1724 fix: project report export.
  dongtai_web/views/project_add.py
Labels: size/XS

#1725 Fix/uniform branches models part
  dongtai_common/migrations/0001_initial.py
  dongtai_common/models/__init__.py
  dongtai_common/models/api_route_v2.py
  dongtai_common/models/integration.py
  dongtai_common/models/license.py
  dongtai_common/models/request_chains.py
  dongtai_common/models/role.py
  dongtai_common/models/share_token.py
Labels: size/XL

#1726 fix:data update
  dongtai_common/migrations/0002_auto_20230726_1433.py
  dongtai_common/migrations/0011_auto_20230814_1537.py
Labels: size/M

#1727 fix: engine hook rule modify.
  dongtai_web/views/engine_hook_rule_modify.py
Labels: size/XS

#1729 fix: package vuls error
  dongtai_common/serializers/assetvulv2.py
Labels: size/XS

#1730 feat: update 1.14.0 strategy.
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_hooktype.json
Labels: size/XL

#1732 fix: delete session if user disable
  dongtai_common/endpoint/__init__.py
Labels: size/XS

#1731 feat: update 1.14.0
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_hooktype.json
Labels: size/L

#1733 fix: delete session if user disable
  dongtai_common/endpoint/__init__.py
Labels: size/S

#1734 feat: deploy uwsgi change process number.
  dongtai_conf/conf/uwsgi.ini
Labels: size/XS

#1735 fix: remove dockerignore
  .dockerignore
Labels: size/XS

#1737 feat: update permission.
  dongtai_common/migrations/0002_auto_20230726_1433.py
Labels: size/XS

#1741 pref: do not check user in protocol api
  dongtai_common/endpoint/__init__.py
Labels: size/S

#1739 fix: remove print
  dongtai_conf/patch/__init__.py
Labels: size/XS

#1753 feat: add session engine
  dongtai_common/migrations/0012_session.py
  dongtai_common/models/__init__.py
  dongtai_common/utils/db_session_engine.py
  dongtai_conf/settings.py
Labels: size/M

#1742 pref: improve app vul list pref
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/XS

#1755 feat: set session expiry
  dongtai_web/views/user_login.py
Labels: size/S

#1754 feat: remove outdate code
  dongtai_common/endpoint/__init__.py
Labels: size/S

#1756 fix: app vul list error
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/XS

#1759 feat: new patch implementation
  dongtai_common/models/user.py
  dongtai_common/permissions/__init__.py
  dongtai_conf/patch/__init__.py
  dongtai_protocol/views/agent_configv2.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/app_vul_summary.py
Labels: size/L

#1762 feat: add login lock status
  dongtai_web/views/user_login.py
Labels: size/XS

#1763 feat: modify project summary api day_num field
  dongtai_web/views/utils/commonstats.py
Labels: size/M

#1766 feat: method pool save
  Pipfile
  Pipfile.lock
  dongtai_common/engine/vul_engine.py
  dongtai_common/migrations/0014_auto_20230828_1132.py
  dongtai_common/models/agent_method_pool.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_web/urls.py
  dongtai_web/views/vul_method_pool_download.py
  pyproject.toml
  requirements.txt
Labels: size/L

#1767 feat: reduce memory usage in vul scan.
  .gitignore
  Pipfile
  Pipfile.lock
  dongtai_common/engine/vul_engine.py
  requirements.txt
Labels: size/L

#1768 feat: modify vul save logic
  dongtai_common/migrations/0015_vul_status.py
  dongtai_common/migrations/0016_auto_20230829_1145.py
  dongtai_common/models/vulnerablity.py
  dongtai_common/utils/const.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/L

#1769 fix: vul method pool error
  dongtai_common/migrations/0017_alter_vulmethodpool_pool_sign.py
  dongtai_common/models/agent_method_pool.py
Labels: size/S

#1771 feat: add has vul method pool field
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/views/vul_details.py
Labels: size/XS

#1772 fix: iast_vulnerability table migration
  dongtai_common/migrations/0016_auto_20230829_1145.py
  dongtai_common/models/vulnerablity.py
Labels: size/XS

#1773 feat: package focus
  dongtai_common/migrations/0018_auto_20230830_1105.py
  dongtai_common/models/assetv2.py
  dongtai_common/models/package_focus.py
  dongtai_web/dongtai_sca/scan/tasks.py
Labels: size/M

#1775 feat: focus package priority
  dongtai_common/migrations/0019_assetv2global_iast_asset__is_focu_31e975_idx.py
  dongtai_common/models/assetv2.py
  dongtai_common/serializers/assetv2.py
  dongtai_web/dongtai_sca/views/newpackage.py
Labels: size/S
