Repository HXSecurity/DongTai, pull requests merged in 2023-05, with the labels that each got.

#1433 fix: engine method pool change to contains.
  dongtai_web/views/engine_method_pool_search.py
Labels: size/S

#1434 fix: agnet register allow report
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/agent_register.py
Labels: size/S

#1435 fix: string parsing error in lookup .
  dongtai_common/utils/db.py
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/XS

#1436 fix: engine method pool change to contains p2.
  dongtai_web/views/engine_method_pool_search.py
Labels: size/M

#1437 feat: agent_v2_allow_report_filter
  dongtai_web/views/agents_v2.py
Labels: size/XS

#1438 fix: add method_pool search timeout .
  dongtai_conf/settings.py
  dongtai_web/views/engine_method_pool_search.py
Labels: size/S

#1441 fix: pep lint fix.
  dongtai_conf/settings.py
Labels: size/XS

#1443 fix: get real uri in redirect case .
  dongtai_engine/signals/handlers/vul_handler.py
Labels: size/XS

#1448 fix: project delete in recognize api .
  dongtai_web/project/recognize_rule.py
Labels: size/S

#1449 fix: project delete in recognize api .
  dongtai_common/utils/stack_recognize.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_web/project/recognize_rule.py
  dongtai_web/views/vul_details.py
Labels: size/M

#1450 fix: project delete in recognize api .
  dongtai_web/project/recognize_rule.py
Labels: size/XS

#1451 fix: recognize rule project id range fix.
  dongtai_web/project/recognize_rule.py
Labels: size/XS

#1452 feat: new strategy rules .
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_hooktype.json
Labels: size/M

#1453 Release-1.11.0
  .github/workflows/teststate.yml
  Pipfile
  Pipfile.lock
  dongtai_common/models/agent.py
  dongtai_common/utils/db.py
  dongtai_common/utils/stack_recognize.py
  dongtai_conf/settings.py
  dongtai_engine/plugins/engine_status_change.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/agent_register.py
  dongtai_protocol/views/except_action.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/project/recognize_rule.py
  dongtai_web/serializers/project.py
  dongtai_web/urls.py
  dongtai_web/views/agents_v2.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/projects.py
  dongtai_web/views/vul_details.py
  requirements.txt
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_hooktype.json
Labels: size/XL

#1454 Release-1.11.0
  .github/workflows/teststate.yml
  Pipfile
  Pipfile.lock
  dongtai_common/models/agent.py
  dongtai_common/utils/db.py
  dongtai_common/utils/stack_recognize.py
  dongtai_conf/settings.py
  dongtai_engine/plugins/engine_status_change.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/narmal_vul_handler.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/agent_register.py
  dongtai_protocol/views/except_action.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/project/recognize_rule.py
  dongtai_web/serializers/project.py
  dongtai_web/urls.py
  dongtai_web/views/agents_v2.py
  dongtai_web/views/engine_method_pool_search.py
  dongtai_web/views/projects.py
  dongtai_web/views/vul_details.py
  requirements.txt
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_hooktype.json
  static/data/python_hooktype.json
Labels: size/XL

#1455 Feat/optimise auth use cache
  dongtai_common/common/utils/__init__.py
  dongtai_protocol/report/handler/report_handler_interface.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
Labels: size/L

#1457 feat: search method pool cache.
  dongtai_common/common/utils/__init__.py
  dongtai_common/models/vulnerablity.py
  dongtai_engine/common/__init__.py
  dongtai_engine/common/queryset.py
  dongtai_engine/tasks.py
  dongtai_web/views/project_add.py
  dongtai_web/views/scan_strategys.py
Labels: size/L

#1460 Ci/update deps celery
  Pipfile
  Pipfile.lock
  dongtai_conf/settings.py
  dongtai_engine/plugins/data_clean.py
  requirements.txt
Labels: size/M

#1462 feat: optimise agent upload.
  dongtai_common/common/utils/__init__.py
  dongtai_conf/celery.py
  dongtai_conf/conf/uwsgi.ini
  dongtai_conf/settings.py
  dongtai_protocol/report/handler/saas_method_pool_handler.py
  dongtai_protocol/views/report_upload.py
Labels: size/M

#1463 feat: optimise agent upload.
  dongtai_conf/settings.py
  dongtai_conf/wsgi.py
Labels: size/XS

#1464 feat: use gevent as default.
  dongtai_conf/conf/uwsgi.ini
  dongtai_conf/wsgi.py
Labels: size/S

#1465 fix: gevent using error.
  dongtai_conf/wsgi.py
Labels: size/XS

#1458 feat: rotate use cache.
  dongtai_common/models/heartbeat.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/heartbeat_handler.py
  test/__init__.py
Labels: size/L

#1467 feat: project timestamp update use async singlton task.
  Pipfile
  Pipfile.lock
  dongtai_conf/celery.py
  dongtai_engine/plugins/project_time_update.py
  dongtai_engine/plugins/strategy_headers.py
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/api_route_handler.py
  requirements.txt
Labels: size/M

#1468 feat: project timestamp update use async singlton task.
  dongtai_engine/signals/handlers/vul_handler.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/api_route_handler.py
Labels: size/XS

#1470 Bugfix/agent id in replay queue
  dongtai_web/views/vul_recheck_v2.py
Labels: size/XS

#1471 Update README.md
  README-zh.md
  README.md
Labels: size/S

#1472 fix: agent heartbeat cache update.
  dongtai_common/common/utils/__init__.py
  dongtai_protocol/report/handler/heartbeat_handler.py
  dongtai_protocol/report/handler/report_handler_interface.py
Labels: size/M

#1475 Feat/new sca impl
  Pipfile
  Pipfile.lock
  dongtai_common/models/asset_vul_v2.py
  dongtai_common/models/assetv2.py
  dongtai_web/dongtai_sca/common/dataclass.py
  dongtai_web/dongtai_sca/scan/utils.py
  dongtai_web/dongtai_sca/urls.py
  dongtai_web/dongtai_sca/views/newpackage.py
  dongtai_web/dongtai_sca/views/newpackagedetail.py
  dongtai_web/dongtai_sca/views/newpackageprojects.py
  dongtai_web/dongtai_sca/views/newpackageprojectversions.py
  dongtai_web/dongtai_sca/views/newpackagesummary.py
  dongtai_web/dongtai_sca/views/newpackagevuldetail.py
  dongtai_web/dongtai_sca/views/newpackagevuls.py
  dongtai_web/utils.py
  requirements.txt
Labels: size/XL
