Repository HXSecurity/DongTai, pull requests merged in 2023-10, with the labels that each got.

#1855 feat: increase buffer size.
  dongtai_conf/conf/uwsgi.ini
Labels: size/XS

#1857 feat: add tantivy search
  .github/actions/setup-python/action.yml
  .github/workflows/nightly.yaml
  .github/workflows/teststate.yml
  Dockerfile
  dongtai_common/migrations/0032_update_vul_index_task.py
  dongtai_common/models/vulnerablity.py
  dongtai_conf/settings.py
  dongtai_engine/tasks.py
  dongtai_protocol/report/handler/auth_info_handler.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/tasks.py
  dongtai_web/apps.py
  dongtai_web/views/agents_delete.py
  dongtai_web/views/user_login.py
  dongtai_web/views/user_register_batch.py
Labels: size/L

#1858 deps: add qrcode dep
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: size/M

#1859 feat: change tantivy index path
  dongtai_conf/settings.py
Labels: size/XS

#1860 Feat/add ldap settings
  Dockerfile
  Pipfile
  Pipfile.lock
  dongtai_common/migrations/0033_auto_20231007_1152.py
  dongtai_common/migrations/0034_auto_20231007_1200.py
  dongtai_common/migrations/0035_alter_user_phone.py
  dongtai_common/models/user.py
  dongtai_conf/settings.py
Labels: size/M

#1861 feat: add update vul tantivy index receiver
  dongtai_conf/settings.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/tasks.py
Labels: size/S

#1862 feat: vul status change msg.
  dongtai_protocol/report/handler/heartbeat_handler.py
  dongtai_web/urls.py
  dongtai_web/utils.py
  dongtai_web/views/vul_status.py
  dongtai_web/views/vul_status_msg.py
  dongtai_web/vul_log/vul_log.py
Labels: size/M

#1864 build(deps): fix deps .
  Pipfile
  Pipfile.lock
Labels: size/XS

#1865 build(deps): fix deps .
  .github/actions/setup-python/action.yml
  requirements.txt
Labels: size/L

#1866 fix: tantivy search error
  dongtai_web/aggr_vul/app_vul_list.py
Labels: size/XS

#1867 build(deps): fix deps .
  dongtai_conf/settings.py
  dongtai_web/views/user_info.py
Labels: size/XS

#1868 fix: tantivy search error
  dongtai_common/models/vulnerablity.py
  dongtai_web/aggr_vul/app_vul_list.py
  dongtai_web/aggr_vul/tasks.py
Labels: size/L

#1869 feat/msg_status_log
  dongtai_web/views/vul_status_msg.py
  dongtai_web/vul_log/vul_log_view.py
Labels: size/S

#1870 feat load vul fix
  Pipfile
  Pipfile.lock
  deploy/commands/management/commands/load_hook_strategy.py
  dongtai_web/vul_log/vul_log_view.py
  requirements.txt
Labels: size/M

#1873 fix: change log level.
  dongtai_engine/tasks.py
  dongtai_protocol/report/report_handler_factory.py
  dongtai_protocol/views/agent_register.py
Labels: size/S

#1874 fix: load hook strategy with dup data.
  deploy/commands/management/commands/load_hook_strategy.py
Labels: size/XS

#1875 fix: tantivy path error
  dongtai_conf/settings.py
Labels: size/XS

#1877 feat: add strategy case.
  dongtai_web/views/engine_hook_rule_add.py
Labels: size/XS

#1878 feat: add vul log time range.
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/vul_log/vul_log_view.py
Labels: size/XS

#1879 Feat/add vul log time range
  dongtai_web/views/engine_hook_rule_add.py
  dongtai_web/vul_log/vul_log_view.py
Labels: size/XS

#1880 Feat/add 1.16 strategy p2
  static/data/go_full_policy.json
  static/data/go_hooktype.json
  static/data/java_full_policy.json
  static/data/java_hooktype.json
  static/data/java_policy.json
  static/data/php_full_policy.json
  static/data/php_hooktype.json
  static/data/python_full_policy.json
  static/data/python_hooktype.json
  static/data/python_policy.json
  static/data/vul_strategy.json
Labels: size/XXL

#1881 fix: vul_log msg record
  dongtai_common/migrations/0036_auto_20230919_1233.py
  dongtai_web/vul_log/vul_log.py
Labels: size/L

#1882 fix: vul_log msg record
  dongtai_common/migrations/0036_auto_20230919_1233.py
Labels: size/XS

#1883 fix: vul_log msg record
  dongtai_common/migrations/0036_auto_20230919_1233.py
Labels: size/XS

#1884 feat: migration permissions.
  dongtai_common/migrations/0036_auto_20230919_1233.py
Labels: size/S
